### ISSUE TITLE
Fast publishing drops messages

### ISSUE THREAD

**Issue by bobbytables** [nats-io/pure-ruby-nats#20] opened 2017-06-26 17:46 UTC
I'm seeing that when I publish messages very quickly using this gem that messages get dropped. When I add `client.flush(1)` the messages go through but this is FAR slower than it should be.

My guess is that the internal fun loop that is waiting for messages is busted. I'm curious why this line checks if the flusher queue is empty:

https://github.com/nats-io/pure-ruby-nats/blob/master/lib/nats/io/client.rb#L261

Thoughts?

**Comment by wallyqs** [comment] 2017-06-26 18:01
Thanks for raising the issue, do you have an example of how to reproduce so that I can take a look?
That check is so that when publishing a command then the flusher starts sending the commands unless there is a pending flush already which would make it flush the buffer.  Using `client.flush(1)` would drain the buffer every time also followed by a ping/pong triggered by the client to ensure that the server has processed the commands, so would be slower because of the roundtrip.

**Comment by bobbytables** [comment] 2017-06-26 18:02
I imagine that we'll need to use something like `at_exit` (https://ruby-doc.org/core-2.2.3/Kernel.html#method-i-at_exit) to avoid losing messages if a process stops.

**Comment by wallyqs** [comment] 2017-06-26 18:04
I wonder if calling `client.close` would help in this case maybe? That also makes a force flush of everything in the buffer before wrapping up the connection to the server.

**Comment by ripienaar** [comment] 2017-06-26 18:05
At exit is annoying because something requested a shutdown and then some random lob does a bunch potentially slow cleanup. 

Best imo to expose the count and relying on clients calling close (which should flush) explicitly

**Comment by bobbytables** [comment] 2017-06-26 19:14
For my case I just added the `conn.close` at the very end of my rake task, but for applications publishing that are long lived that might crash or get SIGTERM sometime (Like a Rails app) it's a bit confusing to know when to call `close`.

**Comment by wallyqs** [comment] 2017-11-17 00:32
Closing with recommendation to use `close` to ensure messages are sent: https://github.com/nats-io/pure-ruby-nats/blob/master/lib/nats/io/client.rb#L524

**Closed by wallyqs** 2017-11-17 00:32 UTC
